{{- if .Values.enabled.awsLoadBalancerController }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: {{ .Values.versions.awsLoadBalancerController | quote }}
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: {{ required "clusterName is required" .Values.clusterName }}
        region: {{ .Values.awsRegion }}
        vpcId: {{ required "vpcId is required" .Values.vpcId }}
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
        replicaCount: 1
        enableServiceMutatorWebhook: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}