image:
  repository: ""
  tag: "bootstrap"

env:
  documentsBucket: ""
  jobsQueueUrl: ""
  awsRegion: us-east-1

database:
  secretName: ""
  secretStore: aws-secretsmanager
  refreshInterval: 1h

scaling:
  minReplicas: 0
  maxReplicas: 10
  queueName: ""
  queueLength: 5
  pollingInterval: 15
  cooldownPeriod: 60